### ISSUE TITLE
ARCameraParam is not defined

### ISSUE THREAD

**Issue by lihuan928** [kalwalt/kalwalt-interactivity-AR#19]
Nft example loading multi markers (multi WebWorkers)：Excuse me, what is the reason why arcameraparam is not defined in this example?

**Comment by kalwalt** [comment]
Hi @lihuan928 welcome on this page! Can you elaborate a bit more your question? Are you getting an error ? Can you post a log in this issue? Which code are you referring exactly? Consider also that some code is a bit experimentally...
Thanks! :slightly_smiling_face:

**Comment by kalwalt** [comment]
Don't use that example, you should use insterad [webarkit/ARnft](https://github.com/webarkit/ARnft) or [jsartoolkitNFT](https://github.com/webarkit/jsartoolkitNFT) both support multi NFT.
