### ISSUE TITLE
Is there a way to get the NFTMarker size?

### ISSUE THREAD

**Issue by Rojke34** [kalwalt/kalwalt-interactivity-AR#21]
I am looking for a way to get the size of my marker(pinball) I want my plane to have the same size as my marker, any suggestions?

thanks!

![IMG_1776](https://user-images.githubusercontent.com/5931219/80872978-06bae880-8c7b-11ea-8116-8ce47b60417e.jpg)

**Comment by kalwalt** [comment]
Hi @Rojke34 Yes there is, You can try my https://github.com/kalwalt/jsartoolkitNFT a lighter version of **Jsartoolkit5** it will give you the dpi, width and height of the marker. check the example. :smile:
