### ISSUE TITLE
nft_pinball_image and nft_pinball_video not working

### ISSUE THREAD

**Issue by jamess922** [kalwalt/kalwalt-interactivity-AR#22]
Hi
     Thank you for your amazing work, and I downloaded this and tried it, but those two demos not working [nft_pinball_image](https://github.com/kalwalt/kalwalt-interactivity-AR/blob/master/nft/nft_pinball_image.html) and [nft_pinball_video](https://github.com/kalwalt/kalwalt-interactivity-AR/blob/master/nft/nft_pinball_video.html) not working，i changed nothing
![微信图片_20200511090907](https://user-images.githubusercontent.com/28625879/81515557-334fbe00-9367-11ea-853f-44f9581cb0a4.jpg)

**Comment by kalwalt** [comment]
Did you tried on localhost or the live code examples https://kalwalt.github.io/kalwalt-interactivity-AR/?

**Comment by kalwalt** [comment]
nft_pinball_image.html worked on localhost but not in gh-pages fixed with https://github.com/kalwalt/kalwalt-interactivity-AR/commit/81370eb6d193ef5065a7cb9f8e149c79e738ccce i don't encounter other issues.
